statement = input("Enter statement to convert to L33T H4X0R format.\n")
statement = statement.replace("a", "4")
statement = statement.replace("b", "8")
statement = statement.replace("e", "3")
statement = statement.replace("l", "1")
statement = statement.replace("o", "0")
statement = statement.replace("s", "5")
statement = statement.replace("t", "7")
print(statement)
